import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";

import Navbar from "@/components/Navbar";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import "../globals.css";
import Footer from "@/components/Footer";
import ToastProvider from "@/lib/providers/ToastProvider";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", '500', '600', '700'],
})

export const metadata: Metadata = {
  title: "Shop Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={poppins.className}>
        <ClerkProvider>
          <ToastProvider/>
          <div className="flex flex-col min-h-screen">
            <div className="flex-grow">
              <Navbar />
              {children}
            </div>
            <Footer />
            <ScrollToTopButton />
          </div>
        </ClerkProvider>
      </body>
    </html>

  );
}
